### ISSUE TITLE
average L obfuscator

### ISSUE THREAD

**Issue by KingKDot** [Heisenberg-tr/Zirinus#1]
Why obf

**Comment by Heisenberg-tr** [comment]
I am thinking of deobf

**Comment by KingKDot** [comment]
Bud u ain't even have to think I can just change exec to print 💀💀💀

**Comment by Heisenberg-tr** [comment]
nope its not working like that

**Comment by Heisenberg-tr** [comment]
unobfuscated the script, have a good day!

**Comment by KingKDot** [comment]
You don't know how the obfuscation works then 💀

**Comment by Heisenberg-tr** [comment]
I don't understand what your purpose is

**Comment by KingKDot** [comment]
Nvm idk why I'm surprised the code is terrible

**Comment by Heisenberg-tr** [comment]
Code is not important, It is important whether it achieves its purpose or not.

**Comment by KingKDot** [comment]
> Code is not important, It is important whether it achieves its purpose or not. 

It is important... your code lacks efficiency and readability. Especially efficiency 😭

**Comment by KingKDot** [comment]
You open a file 4 times and do nothing with it just to make a loading screen 💀

**Comment by Heisenberg-tr** [comment]
> You open a file 4 times and do nothing with it just to make a loading screen 💀

which line?

**Comment by Heisenberg-tr** [comment]
> It is important... your code lacks efficiency and readability. Especially efficiency 

i d

**Comment by KingKDot** [comment]
![image](https://user-images.githubusercontent.com/110929758/214616870-d1d6fe1d-10fd-4332-8226-7ca35aeb2a6a.png)

**Comment by KingKDot** [comment]
I get that it's to make the files but it's poorly made

**Comment by KingKDot** [comment]
Also when your opening files through your code you should use with open rather than a separate open statement

**Comment by Heisenberg-tr** [comment]
This piece of code checks if a file exist (webhook spam feature added in 0.7 git) if file doesnt exist creates 4 txt file in webhook config, not to make a loading screen bruh

**Comment by KingKDot** [comment]
> This piece of code checks if a file exist (webhook spam feature added in 0.7 git) if file doesnt exist creates 4 txt file in webhook config, not to make a loading screen bruh

The print loading text and the variables that aren't being used again is what I'm talking about

**Comment by KingKDot** [comment]
I'm just saying that not this line specifically but other lines you just assign a variable just to open a file while you can use with and it auto closes + more efficient + code is more readable

**Comment by Heisenberg-tr** [comment]
i open file in write mode with same variable bc target is create 4 empty text file and not to use it

**Comment by KingKDot** [comment]
> i open file in write mode with same variable bc target is create 4 empty text file and not to use it

Ok but in other places in the script you should use with

**Comment by KingKDot** [comment]
Also why do you even need to check if they're there? If they download as zip or clone everything will be there

**Comment by Heisenberg-tr** [comment]
Bc of auto update system

**Comment by pogdogpy** [comment]
L code

**Comment by Heisenberg-tr** [comment]
Rewrite is coming with new features:

Message command triggers (like z!stop-spam)
New webhook customization
Setting presets
Send and view message from terminal

And more...

**Comment by pogdogpy** [comment]
didnt ask delete ur github die please L code give up xD

**Comment by Heisenberg-tr** [comment]
do you think you are funny? You are just a rat.
